[package]
name = "bellman_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = "0.14.0"
bls12_381 = "0.8"
hex-literal = "0.3"
rand = "0.8"
sha2 = "0.10"
ff = "0.13"
